/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as BudgetIndexRouteImport } from './routes/budget/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ExpenseAddRouteImport } from './routes/expense/add'
import { Route as SettingsWalletsIndexRouteImport } from './routes/settings/wallets/index'
import { Route as SettingsExpenseCategoryIndexRouteImport } from './routes/settings/expense-category/index'
import { Route as SettingsCurrencyIndexRouteImport } from './routes/settings/currency/index'
import { Route as SettingsWalletsAddRouteImport } from './routes/settings/wallets/add'
import { Route as SettingsSecurityPinRouteImport } from './routes/settings/security/pin'
import { Route as SettingsExpenseCategoryAddRouteImport } from './routes/settings/expense-category/add'
import { Route as SettingsWalletsEditIdRouteImport } from './routes/settings/wallets/edit.$id'
import { Route as SettingsExpenseCategoryEditIdRouteImport } from './routes/settings/expense-category/edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetIndexRoute = BudgetIndexRouteImport.update({
  id: '/budget/',
  path: '/budget/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseAddRoute = ExpenseAddRouteImport.update({
  id: '/expense/add',
  path: '/expense/add',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWalletsIndexRoute = SettingsWalletsIndexRouteImport.update({
  id: '/settings/wallets/',
  path: '/settings/wallets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExpenseCategoryIndexRoute =
  SettingsExpenseCategoryIndexRouteImport.update({
    id: '/settings/expense-category/',
    path: '/settings/expense-category/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsCurrencyIndexRoute = SettingsCurrencyIndexRouteImport.update({
  id: '/settings/currency/',
  path: '/settings/currency/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWalletsAddRoute = SettingsWalletsAddRouteImport.update({
  id: '/settings/wallets/add',
  path: '/settings/wallets/add',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityPinRoute = SettingsSecurityPinRouteImport.update({
  id: '/settings/security/pin',
  path: '/settings/security/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExpenseCategoryAddRoute =
  SettingsExpenseCategoryAddRouteImport.update({
    id: '/settings/expense-category/add',
    path: '/settings/expense-category/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsWalletsEditIdRoute = SettingsWalletsEditIdRouteImport.update({
  id: '/settings/wallets/edit/$id',
  path: '/settings/wallets/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExpenseCategoryEditIdRoute =
  SettingsExpenseCategoryEditIdRouteImport.update({
    id: '/settings/expense-category/edit/$id',
    path: '/settings/expense-category/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expense/add': typeof ExpenseAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/budget/': typeof BudgetIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/settings/expense-category/add': typeof SettingsExpenseCategoryAddRoute
  '/settings/security/pin': typeof SettingsSecurityPinRoute
  '/settings/wallets/add': typeof SettingsWalletsAddRoute
  '/settings/currency/': typeof SettingsCurrencyIndexRoute
  '/settings/expense-category/': typeof SettingsExpenseCategoryIndexRoute
  '/settings/wallets/': typeof SettingsWalletsIndexRoute
  '/settings/expense-category/edit/$id': typeof SettingsExpenseCategoryEditIdRoute
  '/settings/wallets/edit/$id': typeof SettingsWalletsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expense/add': typeof ExpenseAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/budget': typeof BudgetIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/settings/expense-category/add': typeof SettingsExpenseCategoryAddRoute
  '/settings/security/pin': typeof SettingsSecurityPinRoute
  '/settings/wallets/add': typeof SettingsWalletsAddRoute
  '/settings/currency': typeof SettingsCurrencyIndexRoute
  '/settings/expense-category': typeof SettingsExpenseCategoryIndexRoute
  '/settings/wallets': typeof SettingsWalletsIndexRoute
  '/settings/expense-category/edit/$id': typeof SettingsExpenseCategoryEditIdRoute
  '/settings/wallets/edit/$id': typeof SettingsWalletsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expense/add': typeof ExpenseAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/budget/': typeof BudgetIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/settings/expense-category/add': typeof SettingsExpenseCategoryAddRoute
  '/settings/security/pin': typeof SettingsSecurityPinRoute
  '/settings/wallets/add': typeof SettingsWalletsAddRoute
  '/settings/currency/': typeof SettingsCurrencyIndexRoute
  '/settings/expense-category/': typeof SettingsExpenseCategoryIndexRoute
  '/settings/wallets/': typeof SettingsWalletsIndexRoute
  '/settings/expense-category/edit/$id': typeof SettingsExpenseCategoryEditIdRoute
  '/settings/wallets/edit/$id': typeof SettingsWalletsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expense/add'
    | '/profile/edit'
    | '/budget/'
    | '/profile/'
    | '/reports/'
    | '/settings/'
    | '/transactions/'
    | '/settings/expense-category/add'
    | '/settings/security/pin'
    | '/settings/wallets/add'
    | '/settings/currency/'
    | '/settings/expense-category/'
    | '/settings/wallets/'
    | '/settings/expense-category/edit/$id'
    | '/settings/wallets/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expense/add'
    | '/profile/edit'
    | '/budget'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/settings/expense-category/add'
    | '/settings/security/pin'
    | '/settings/wallets/add'
    | '/settings/currency'
    | '/settings/expense-category'
    | '/settings/wallets'
    | '/settings/expense-category/edit/$id'
    | '/settings/wallets/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/expense/add'
    | '/profile/edit'
    | '/budget/'
    | '/profile/'
    | '/reports/'
    | '/settings/'
    | '/transactions/'
    | '/settings/expense-category/add'
    | '/settings/security/pin'
    | '/settings/wallets/add'
    | '/settings/currency/'
    | '/settings/expense-category/'
    | '/settings/wallets/'
    | '/settings/expense-category/edit/$id'
    | '/settings/wallets/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpenseAddRoute: typeof ExpenseAddRoute
  ProfileEditRoute: typeof ProfileEditRoute
  BudgetIndexRoute: typeof BudgetIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  SettingsExpenseCategoryAddRoute: typeof SettingsExpenseCategoryAddRoute
  SettingsSecurityPinRoute: typeof SettingsSecurityPinRoute
  SettingsWalletsAddRoute: typeof SettingsWalletsAddRoute
  SettingsCurrencyIndexRoute: typeof SettingsCurrencyIndexRoute
  SettingsExpenseCategoryIndexRoute: typeof SettingsExpenseCategoryIndexRoute
  SettingsWalletsIndexRoute: typeof SettingsWalletsIndexRoute
  SettingsExpenseCategoryEditIdRoute: typeof SettingsExpenseCategoryEditIdRoute
  SettingsWalletsEditIdRoute: typeof SettingsWalletsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget/': {
      id: '/budget/'
      path: '/budget'
      fullPath: '/budget/'
      preLoaderRoute: typeof BudgetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/add': {
      id: '/expense/add'
      path: '/expense/add'
      fullPath: '/expense/add'
      preLoaderRoute: typeof ExpenseAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/wallets/': {
      id: '/settings/wallets/'
      path: '/settings/wallets'
      fullPath: '/settings/wallets/'
      preLoaderRoute: typeof SettingsWalletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/expense-category/': {
      id: '/settings/expense-category/'
      path: '/settings/expense-category'
      fullPath: '/settings/expense-category/'
      preLoaderRoute: typeof SettingsExpenseCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/currency/': {
      id: '/settings/currency/'
      path: '/settings/currency'
      fullPath: '/settings/currency/'
      preLoaderRoute: typeof SettingsCurrencyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/wallets/add': {
      id: '/settings/wallets/add'
      path: '/settings/wallets/add'
      fullPath: '/settings/wallets/add'
      preLoaderRoute: typeof SettingsWalletsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security/pin': {
      id: '/settings/security/pin'
      path: '/settings/security/pin'
      fullPath: '/settings/security/pin'
      preLoaderRoute: typeof SettingsSecurityPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/expense-category/add': {
      id: '/settings/expense-category/add'
      path: '/settings/expense-category/add'
      fullPath: '/settings/expense-category/add'
      preLoaderRoute: typeof SettingsExpenseCategoryAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/wallets/edit/$id': {
      id: '/settings/wallets/edit/$id'
      path: '/settings/wallets/edit/$id'
      fullPath: '/settings/wallets/edit/$id'
      preLoaderRoute: typeof SettingsWalletsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/expense-category/edit/$id': {
      id: '/settings/expense-category/edit/$id'
      path: '/settings/expense-category/edit/$id'
      fullPath: '/settings/expense-category/edit/$id'
      preLoaderRoute: typeof SettingsExpenseCategoryEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpenseAddRoute: ExpenseAddRoute,
  ProfileEditRoute: ProfileEditRoute,
  BudgetIndexRoute: BudgetIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  SettingsExpenseCategoryAddRoute: SettingsExpenseCategoryAddRoute,
  SettingsSecurityPinRoute: SettingsSecurityPinRoute,
  SettingsWalletsAddRoute: SettingsWalletsAddRoute,
  SettingsCurrencyIndexRoute: SettingsCurrencyIndexRoute,
  SettingsExpenseCategoryIndexRoute: SettingsExpenseCategoryIndexRoute,
  SettingsWalletsIndexRoute: SettingsWalletsIndexRoute,
  SettingsExpenseCategoryEditIdRoute: SettingsExpenseCategoryEditIdRoute,
  SettingsWalletsEditIdRoute: SettingsWalletsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
